ALTER TABLE videos ADD COLUMN IF NOT EXISTS processing_progress INTEGER DEFAULT 0;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS sprite_sheet_url TEXT DEFAULT '';
ALTER TABLE videos ADD COLUMN IF NOT EXISTS sprite_vtt_url TEXT DEFAULT '';
